/*
 MIT License

 (C) Copyright 2022-2025 Hewlett Packard Enterprise Development LP

 Permission is hereby granted, free of charge, to any person obtaining a
 copy of this software and associated documentation files (the "Software"),
 to deal in the Software without restriction, including without limitation
 the rights to use, copy, modify, merge, publish, distribute, sublicense,
 and/or sell copies of the Software, and to permit persons to whom the
 Software is furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included
 in all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 OTHER DEALINGS IN THE SOFTWARE.
*/

package initialize

import (
	"fmt"
	"net"
	"net/netip"
	"path/filepath"
	"strings"
	"text/template"

	slsCommon "github.com/Cray-HPE/hms-sls/v2/pkg/sls-common"

	"github.com/spf13/viper"

	"github.com/Cray-HPE/cray-site-init/internal/files"
	"github.com/Cray-HPE/cray-site-init/pkg/networking"
)

// SubnetConfigDHCPOnlyTemplate handles subnet definitions with reduced DHCP options.
var SubnetConfigDHCPOnlyTemplate = []byte(`
{{- /* remove leading whitespace */ -}}
#
## This file was generated by cray-site-init.
## Version: {{ .Version }}
## Generated time: {{ .Timestamp }}
#
# {{.Data.Network.Name}}:
server=/{{.Data.Network.Name | lower}}/
address=/{{.Data.Network.Name | lower}}/
dhcp-option=interface:{{.Data.Interface}},option:domain-search,{{.Data.Network.Name | lower}}
interface-name=pit.{{.Data.Network.Name | lower}},{{.Data.Interface}}
interface={{.Data.Interface}}
cname=packages.{{.Data.Network.Name | lower}},pit.{{.Data.Network.Name | lower}}
cname=registry.{{.Data.Network.Name | lower}},pit.{{.Data.Network.Name | lower}}
dhcp-option=interface:{{.Data.Interface}},option:router,{{.Data.Subnet.Gateway}}
dhcp-range=interface:{{.Data.Interface}},{{.Data.Subnet.DHCPStart}},{{.Data.Subnet.DHCPEnd}},10m
`)

// SubnetConfigTemplate handles subnet definitions for DNSMasq.
var SubnetConfigTemplate = []byte(`
{{- /* remove leading whitespace */ -}}
#
## This file was generated by cray-site-init.
## Version: {{ .Version }}
## Generated time: {{ .Timestamp }}
#
# {{.Data.Network.Name}}:
server=/{{.Data.Network.Name | lower}}/
address=/{{.Data.Network.Name | lower}}/
domain=nmn,{{.Data.NetworkStart}},{{.Data.NetworkEnd}},local
interface-name=pit.{{.Data.Network.Name | lower}},{{.Data.Interface}}
dhcp-option=interface:{{.Data.Interface}},option:domain-search,{{.Data.Network.Name | lower}}
interface={{.Data.Interface}}
cname=packages.{{.Data.Network.Name | lower}},pit.{{.Data.Network.Name | lower}}
{{ if eq .Data.Network.Name "MTL" -}}
cname=packages.local,pit.{{.Data.Network.Name | lower}}
{{ end -}}
cname=registry.{{.Data.Network.Name | lower}},pit.{{.Data.Network.Name | lower}}
dhcp-option=interface:{{.Data.Interface}},option:dns-server,{{.Data.Network.PITServer}}
dhcp-option=interface:{{.Data.Interface}},option:ntp-server,{{.Data.Network.PITServer}}
dhcp-option=interface:{{.Data.Interface}},option:router,{{.Data.Subnet.Gateway}}
dhcp-range=interface:{{.Data.Interface}},{{.Data.Subnet.DHCPStart}},{{.Data.Subnet.DHCPEnd}},10m
`)

// StaticConfigTemplate manages the static portion of the DNSMasq configuration
// Systems with onboard NICs will have a MTL MAC. Others will also use the NMN
var StaticConfigTemplate = []byte(`
{{- /* remove leading whitespace */ -}}
#
## This file was generated by cray-site-init.
## Version: {{ .Version }}
## Generated time: {{ .Timestamp }}
#
# Static Configurations
{{range .Data.NCNS}}
# DHCP Entries for {{.Hostname}}
dhcp-host=id:{{.Xname}},set:{{.Hostname}},{{.Bond0Mac0}},{{.Bond0Mac1}},{{.MtlIP}},{{.Hostname}},20m # MTL
dhcp-host=id:{{.Xname}},set:{{.Hostname}},{{.Bond0Mac0}},{{.Bond0Mac1}},{{.NmnIP}},{{.Hostname}},20m # Bond0 Mac0/Mac1
dhcp-host=id:{{.Xname}},set:{{.Hostname}},{{.Bond0Mac0}},{{.Bond0Mac1}},{{.HmnIP}},{{.Hostname}},20m # HMN
{{ if eq $.Data.BICAN "CAN" -}}
dhcp-host=id:{{.Xname}},set:{{.Hostname}},{{.Bond0Mac0}},{{.Bond0Mac1}},{{.CanIP}},{{.Hostname}},20m # CAN
{{ end -}}
dhcp-host={{.BmcMac}},{{.BmcIP}},{{.Hostname}}-mgmt,20m #HMN
# Host Record Entries for {{.Hostname}}
{{ if eq $.Data.BICAN "CAN" -}}
host-record={{.Hostname}},{{.Hostname}}.can,{{.CanIP}}
{{ end -}}
host-record={{.Hostname}},{{.Hostname}}.hmn,{{.HmnIP}}
host-record={{.Hostname}},{{.Hostname}}.nmn,{{.NmnIP}}
host-record={{.Hostname}},{{.Hostname}}.mtl,{{.MtlIP}}
host-record={{.Xname}},{{.Hostname}}.nmn,{{.NmnIP}}
host-record={{.Hostname}}-mgmt,{{.Hostname}}-mgmt.hmn,{{.BmcIP}}
# Override root-path with {{.Hostname}}'s xname
dhcp-option-force=tag:{{.Hostname}},17,{{.Xname}}
{{end}}
# Virtual IP Addresses for k8s and the rados gateway
host-record=kubeapi-vip,kubeapi-vip.nmn,{{.Data.KUBEVIP}} # k8s-virtual-ip
host-record=rgw-vip,rgw-vip.nmn,{{.Data.RGWVIP}} # rgw-virtual-ip
host-record={{.Data.APIGWALIASES}},{{.Data.APIGWIP}} # api gateway

cname=kubernetes-api.vshasta.io,ncn-m001
`)

// DNSMasqBootstrapNetwork holds information for configuring DNSMasq on the LiveCD
type DNSMasqBootstrapNetwork struct {
	NetworkStart netip.Addr
	NetworkEnd   netip.Addr
	Network      networking.IPNetwork
	Subnet       slsCommon.IPSubnet
	Interface    string
}

type DNSMasqStatics struct {
	NCNS         []LogicalNCN
	KUBEVIP      string
	RGWVIP       string
	APIGWALIASES string
	APIGWIP      string
	BICAN        string
}

// WriteDNSMasqConfig writes the dnsmasq configuration files necessary for installation
func WriteDNSMasqConfig(
	path string, v *viper.Viper, bootstrap []LogicalNCN, networks map[string]*networking.IPNetwork,
) (err error) {
	for i, tmpNcn := range bootstrap {
		for _, tmpNet := range tmpNcn.Networks {
			if strings.ToUpper(tmpNet.NetworkName) == "NMN" {
				tmpNcn.NmnIP = tmpNet.IPv4Address.String()
			}
			if strings.ToUpper(tmpNet.NetworkName) == "CAN" {
				tmpNcn.CanIP = tmpNet.IPv4Address.String()
			}
			if strings.ToUpper(tmpNet.NetworkName) == "MTL" {
				tmpNcn.MtlIP = tmpNet.IPv4Address.String()
			}
			if strings.ToUpper(tmpNet.NetworkName) == "HMN" {
				tmpNcn.HmnIP = tmpNet.IPv4Address.String()
			}
		}
		bootstrap[i] = tmpNcn
	}
	funcMap := template.FuncMap{
		// The name "title" is what the function will be called in the template text.
		"lower": strings.ToLower,
	}

	// Shasta Networks:
	netCMN := template.Must(template.New("cmnconfig").Funcs(funcMap).Parse(string(SubnetConfigDHCPOnlyTemplate)))
	netHMN := template.Must(template.New("hmnconfig").Funcs(funcMap).Parse(string(SubnetConfigTemplate)))
	netNMN := template.Must(template.New("nmnconfig").Funcs(funcMap).Parse(string(SubnetConfigTemplate)))
	netMTL := template.Must(template.New("mtlconfig").Funcs(funcMap).Parse(string(SubnetConfigTemplate)))
	err = writeConfig(
		"CMN",
		path,
		*netCMN,
		networks,
	)
	if err != nil {
		return fmt.Errorf(
			"failed to write CMN DNSMasq config because %v",
			err,
		)
	}
	err = writeConfig(
		"HMN",
		path,
		*netHMN,
		networks,
	)
	if err != nil {
		return fmt.Errorf(
			"failed to write HMN DNSMasq config because %v",
			err,
		)
	}
	err = writeConfig(
		"NMN",
		path,
		*netNMN,
		networks,
	)
	if err != nil {
		return fmt.Errorf(
			"failed to write NMN DNSMasq config because %v",
			err,
		)
	}
	err = writeConfig(
		"MTL",
		path,
		*netMTL,
		networks,
	)
	if err != nil {
		return fmt.Errorf(
			"failed to write MTL DNSMasq config because %v",
			err,
		)
	}

	bicanNetworkName := v.GetString("bican-user-network-name")
	var kubevip, rgwvip string
	nmnSubnet, _ := networks["NMN"].LookUpSubnet("bootstrap_dhcp")
	for _, reservation := range nmnSubnet.IPReservations {
		if reservation.Name == "kubeapi-vip" {
			kubevip = reservation.IPAddress.String()
		}
		if reservation.Name == "rgw-vip" {
			rgwvip = reservation.IPAddress.String()
		}
	}

	var apigwAliases, apigwIP string
	nmnlbNet, _ := networks["NMNLB"].LookUpSubnet("nmn_metallb_address_pool")
	apigw := nmnlbNet.ReservationsByName()["istio-ingressgateway"]
	apigwAliases = strings.Join(
		apigw.Aliases,
		",",
	)
	apigwIP = apigw.IPAddress.String()

	if bicanNetworkName == "CAN" || v.GetBool("retain-unused-user-network") {
		netCAN := template.Must(template.New("canconfig").Funcs(funcMap).Parse(string(SubnetConfigDHCPOnlyTemplate)))
		err := writeConfig(
			bicanNetworkName,
			path,
			*netCAN,
			networks,
		)
		if err != nil {
			return fmt.Errorf(
				"failed to write CAN DNSMasq config because %v",
				err,
			)
		}
	}

	data := MakeTemplateData(
		DNSMasqStatics{
			NCNS:         bootstrap,
			KUBEVIP:      kubevip,
			RGWVIP:       rgwvip,
			APIGWALIASES: apigwAliases,
			APIGWIP:      apigwIP,
			BICAN:        bicanNetworkName,
		},
	)
	// Expected NCNs (and other devices) reserved DHCP leases:
	netIPAM := template.Must(template.New("statics").Parse(string(StaticConfigTemplate)))
	err = files.WriteTemplate(
		filepath.Join(
			path,
			"dnsmasq.d/statics.conf",
		),
		netIPAM,
		data,
	)
	if err != nil {
		return fmt.Errorf(
			"failed to write DNSMasq statics.conf because %v",
			err,
		)
	}
	return err
}

func writeConfig(
	name, path string, tpl template.Template, networks map[string]*networking.IPNetwork,
) (err error) {
	// Pointer to the IPNetwork
	tempNet := networks[name]

	v := viper.GetViper()

	// Pointer to the subnet
	bootstrapSubnet, _ := tempNet.LookUpSubnet("bootstrap_dhcp")
	// Create a subnet copy (avoid modifying the base Data with dnsmasq overrides)
	tempSubnet := *bootstrapSubnet

	// Look up the PIT IP for the network
	for _, reservation := range tempSubnet.IPReservations {
		if reservation.Name == v.GetString("install-ncn") {
			tempNet.PITServer = reservation.IPAddress.String()
		}
	}
	if strings.ToLower(tempNet.Name) == "can" {
		tempSubnet.Gateway = net.ParseIP(v.GetString("can-gateway"))
	}
	if strings.ToLower(tempNet.Name) == "cmn" {
		tempSubnet.Gateway = net.ParseIP(v.GetString("cmn-gateway4"))
	}

	nmnLBSubnet, _ := networks["NMNLB"].LookUpSubnet("nmn_metallb_address_pool")
	tempNet.DNSServer = nmnLBSubnet.LookupReservation("unbound").IPAddress.String()

	interfaceName, _ := tempNet.GenInterfaceName(&tempSubnet)
	prefix4, err := netip.ParsePrefix(tempNet.CIDR4)
	if err != nil {
		return fmt.Errorf(
			"failed to parse %s CIDR because %v ",
			tempNet.CIDR4,
			err,
		)
	}
	networkEnd, err := networking.Broadcast(prefix4)
	if err != nil {
		return fmt.Errorf(
			"failed to find broadcast address for %s because %v ",
			tempNet.CIDR4,
			err,
		)
	}
	bootstrapNetwork := MakeTemplateData(
		DNSMasqBootstrapNetwork{
			NetworkStart: prefix4.Addr(),
			NetworkEnd:   networkEnd,
			Network:      *tempNet,
			Interface:    interfaceName,
			Subnet:       tempSubnet,
		},
	)

	err = files.WriteTemplate(
		filepath.Join(
			path,
			fmt.Sprintf(
				"dnsmasq.d/%v.conf",
				name,
			),
		),
		&tpl,
		bootstrapNetwork,
	)
	if err != nil {
		err = fmt.Errorf(
			"failed to write dnsmasq config for %s because %v",
			path,
			err,
		)
	}
	return err
}
