/*
Copyright 2021 Hewlett Packard Enterprise Development LP
*/

package cmd

import (
	"encoding/csv"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"sort"
	"strings"
	"unicode"

	"github.com/Cray-HPE/cray-site-init/pkg/csi"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
	"github.com/xeipuuv/gojsonschema"
	"gopkg.in/yaml.v3"
)

const schemaFile = "internal/files/shcd-schema.json"
const hmn_connections = "hmn_connections.json"
const switch_metadata = "switch_metadata.csv"
const application_node_config = "application_node_config.yaml"

var createHMN, createSM, createANC bool

var prefixSubroleMapIn map[string]string

// initCmd represents the init command
var shcdCmd = &cobra.Command{
	Use:   "shcd FILEPATH",
	Short: "Generates hmn_connections.json, switch_metadata.csv, and application_node_config.yaml from an SHCD JSON file",
	Long: `Generates hmn_connections.json, switch_metadata.csv, application_node_config.yaml from an SHCD JSON file.

	It accepts only a valid JSON file, generated by 'canu', which is creates a machine-
	readable format understood by csi.  It is checked against a pre-defined schema and
	if it adhere's to it, it generates the necessary seed files.
	`,
	Args: cobra.MinimumNArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		v := viper.GetViper()
		v.BindPFlags(cmd.Flags())

		// Validate the file passed against the pre-defined schema
		validSHCD, err := ValidateSchema(args[0], schemaFile)

		if err != nil {
			log.Fatalf(err.Error())
		}

		// If the file meets the schema criteria
		if validSHCD {

			// Open the file since we know it is valid
			shcdFile, err := ioutil.ReadFile(args[0])

			if err != nil {
				log.Fatalf(err.Error())
			}

			// Parse the JSON and return an Shcd object
			s, err := ParseSHCD(shcdFile)

			if err != nil {
				log.Fatalf(err.Error())
			}

			// Pretty print the structured data
			shcd, err := json.MarshalIndent(&s, "", " ")

			if err != nil {
				log.Fatalf(err.Error())
			}

			// TODO: instead of printing the entire thing, create some of the seed file automatically
			fmt.Println(string(shcd))

			if v.IsSet("hmn-connections") {

				createHMNSeed(s, hmn_connections)

			}

			if v.IsSet("switch-metadata") {

				createSwitchSeed(s, switch_metadata)

			}

			if v.IsSet("application-node-config") {

				createANCSeed(s, application_node_config)

			}

		} else {

			log.Printf("- %s\n", err)

			if err != nil {
				log.Fatalf(err.Error())
			}

		}
	},
}

func init() {
	shcdCmd.DisableAutoGenTag = true
	shcdCmd.Flags().SortFlags = true
	shcdCmd.Flags().BoolVarP(&createHMN, "hmn-connections", "H", false, "Generate the hmn_connections.json file")
	shcdCmd.Flags().BoolVarP(&createSM, "switch-metadata", "S", false, "Generate the switch_metadata.csv file")
	shcdCmd.Flags().BoolVarP(&createANC, "application-node-config", "A", false, "Generate the application_node_config.yaml file")
	shcdCmd.Flags().StringToStringVarP(&prefixSubroleMapIn, "prefix-subrole-mapping", "M", map[string]string{}, "Specify one or more additional <Prefix>=<Subrole> mappings to use when generating application_node_config.yaml. Multiple mappings can be specified in the format of <prefix1>=<subrole1>,<prefix2>=<subrole2>")
}

// The Shcd type represents the entire machine-readable SHCD inside a go struct
type Shcd []Id

// The Id type represents all of the information needed for
type Id struct {
	Architecture string   `json:"architecture"`
	CommonName   string   `json:"common_name"`
	ID           int      `json:"id"`
	Location     Location `json:"location"`
	Model        string   `json:"model"`
	Ports        []Port   `json:"ports"`
	Type         string   `json:"type"`
	Vendor       string   `json:"vendor"`
}

// The Port type defines where things are plugged in
type Port struct {
	DestNodeID int    `json:"destination_node_id"`
	DestPort   int    `json:"destination_port"`
	DestSlot   string `json:"destination_slot"`
	Port       int    `json:"port"`
	Slot       string `json:"slot"`
	Speed      int    `json:"speed"`
}

type Location struct {
	Elevation string `json:"elevation"`
	Rack      string `json:"rack"`
}

// HMNConnections type is the go equivalent structure of hmn_connections.json
type HMNConnections []HMNComponent

// HMNComponent is an individual component in the HMNConnections slice
type HMNComponent struct {
	Source              string
	SourceRack          string
	SourceLocation      string
	SourceSubLocation   string
	DestinationRack     string
	DestinationLocation int
	DestinationPort     string
}

// SwitchMetadata type is the go equivalent structure of switch_metadata.csv
type SwitchMetadata []Switch

// Switch is a row in switch_metadata.csv
type Switch struct {
	Xname string
	Type  string
	Brand string
}

// createSwitchSeed creates switch_metadata.csv using information from the shcd
func createSwitchSeed(shcd Shcd, f string) {
	var switches SwitchMetadata

	// For each entry in the SHCD
	for i := range shcd {

		// Create a new Switch type and append it to the SwitchMetadata slice
		switches = append(switches, Switch{
			Xname: shcd[i].Location.Rack,
			Type:  shcd[i].Type,
			Brand: shcd[i].Vendor,
		})

	}

	// When writing to csv, the first row should be the headers
	headers := []string{"Switch Xname", "Type", "Brand"}

	// Set up the records we need to write to the file
	// To begin, this contains the headers
	records := [][]string{headers}

	// Then create a new slice with the three pieces of information needed
	for _, v := range switches {
		row := []string{v.Xname, v.Type, v.Brand}
		// Append it to the records slice under the column headers
		records = append(records, row)
	}

	// Create the file object
	sm, err := os.Create(switch_metadata)

	if err != nil {
		log.Fatalln(err)
	}

	defer sm.Close()

	// Create a writer, which will write the data to the file
	writer := csv.NewWriter(sm)

	defer writer.Flush()

	if err != nil {
		log.Fatalln(err)
	}

	// For each item in the records slice
	for _, v := range records {
		// Write it to the csv file
		if err := writer.Write(v); err != nil {
			log.Fatalln(err)
		}
	}

	// Let the user know the file was created
	log.Printf("Created %v from SHCD data\n", switch_metadata)
}

// createHMNSeed creates hmn_connections.json using information from the shcd
func createHMNSeed(shcd Shcd, f string) {

	var hmn HMNConnections

	// For each entry in the shcd
	for i := range shcd {

		// Create a new HMNComponent type and append it to the HMNConnections slice
		hmn = append(hmn, HMNComponent{
			Source:         shcd[i].CommonName,
			SourceRack:     shcd[i].Location.Rack,
			SourceLocation: shcd[i].Location.Elevation,
		})

	}

	// Indent the file for better human-readability
	file, _ := json.MarshalIndent(hmn, "", " ")

	// Write the file to disk
	_ = ioutil.WriteFile(hmn_connections, file, 0644)

	log.Printf("Created %v from SHCD data\n", hmn_connections)

}

// createANCSeed creates application_node_config.yaml using information from the shcd
func createANCSeed(shcd Shcd, f string) error {

	var (
		comment1 string = "# Additional application node prefixes to match in the hmn_connections.json file"
		comment2 string = "\n# Additional HSM SubRoles"
		comment3 string = "\n# Application Node aliases"
	)

	anc := csi.SLSGeneratorApplicationNodeConfig{
		Prefixes:          make([]string, 0, 1),
		PrefixHSMSubroles: make(map[string]string),
		Aliases:           make(map[string][]string),
	}
	prefixMap := make(map[string]string)

	// Search the shcd for Application Nodes
	for _, id := range shcd {
		source := strings.ToLower(id.CommonName)
		idType := strings.ToLower(id.Type)
		if idType != "server" ||
			strings.Contains(source, "ncn") {
			continue
		}

		found := false
		// Match custom prefix<->subrole mappings first before default ones
		if len(prefixSubroleMapIn) > 0 {
			for prefix, subrole := range prefixSubroleMapIn {
				if strings.HasPrefix(source, prefix) {
					found = true
					prefixMap[prefix] = subrole
					break
				}
			}
		}
		if !found {
			// Match default prefix<->subrole mappings
			for _, prefix := range csi.DefaultApplicationNodePrefixes {
				if strings.HasPrefix(source, prefix) {
					found = true
					break
				}
			}
		}

		if !found {
			// Add a placeholder for unmatched prefixes to have the admin
			// assign a subrole to use for that prefix.
			f := strings.FieldsFunc(source,
				func(c rune) bool { return !unicode.IsLetter(c) })
			prefixMap[f[0]] = "~fixme~"
		}

		location := strings.TrimFunc(id.Location.Elevation,
			func(r rune) bool { return unicode.IsLetter(r) })

		// Construct the xname
		xname := ""
		if strings.HasSuffix(strings.ToLower(id.Location.Elevation), "l") {
			xname = fmt.Sprintf("%sc0s%sb1n0", id.Location.Rack, location)
		} else if strings.HasSuffix(strings.ToLower(id.Location.Elevation), "r") {
			xname = fmt.Sprintf("%sc0s%sb2n0", id.Location.Rack, location)
		} else {
			xname = fmt.Sprintf("%sc0s%sb0n0", id.Location.Rack, location)
		}

		// List Aliases
		if _, ok := anc.Aliases[xname]; !ok {
			anc.Aliases[xname] = make([]string, 0, 1)
		}
		anc.Aliases[xname] = append(anc.Aliases[xname], source)
	}

	// Build the 'Prefixes' list and the 'PrefixHSMSubroles' map
	for prefix, subrole := range prefixMap {
		anc.Prefixes = append(anc.Prefixes, prefix)
		anc.PrefixHSMSubroles[prefix] = subrole
		// Warn the admin if there are any prefixes that have no subrole
		if subrole == csi.SubrolePlaceHolder {
			log.Printf("WARNING: Prefix '%s' has no subrole mapping. Replace `%s` placeholder with a valid subrole in the resulting %s.\n", prefix, csi.SubrolePlaceHolder, application_node_config)
		}
	}

	// Format the yaml
	prefixNodes := []*yaml.Node{}
	prefixHSMSubroleNodes := []*yaml.Node{}
	sort.Strings(anc.Prefixes)
	for _, prefix := range anc.Prefixes {
		n := yaml.Node{Kind: yaml.ScalarNode, Value: prefix}
		prefixNodes = append(prefixNodes, &n)

		subrole := anc.PrefixHSMSubroles[prefix]
		kn := yaml.Node{Kind: yaml.ScalarNode, Value: prefix}
		vn := yaml.Node{Kind: yaml.ScalarNode, Value: subrole}
		prefixHSMSubroleNodes = append(prefixHSMSubroleNodes, &kn, &vn)
	}
	prefixes := yaml.Node{Kind: yaml.SequenceNode, Content: prefixNodes}
	prefixesTitle := yaml.Node{Kind: yaml.ScalarNode, Value: "prefixes", HeadComment: comment1}
	prefixHSMSubroles := yaml.Node{Kind: yaml.MappingNode, Content: prefixHSMSubroleNodes}
	prefixHSMSubrolesTitle := yaml.Node{Kind: yaml.ScalarNode, Value: "prefix_hsm_subroles", HeadComment: comment2}

	aliasNodes := []*yaml.Node{}
	aliasArray := make([]string, 0, 1)
	for xname, _ := range anc.Aliases {
		aliasArray = append(aliasArray, xname)
	}
	sort.Strings(aliasArray)
	for _, xname := range aliasArray {
		aliasList := anc.Aliases[xname]
		kn := yaml.Node{Kind: yaml.ScalarNode, Value: xname}
		aliasSubNodes := []*yaml.Node{}
		for _, alias := range aliasList {
			n := yaml.Node{Kind: yaml.ScalarNode, Style: yaml.DoubleQuotedStyle, Value: alias}
			aliasSubNodes = append(aliasSubNodes, &n)
		}
		vn := yaml.Node{Kind: yaml.SequenceNode, Style: yaml.FlowStyle, Content: aliasSubNodes}
		aliasNodes = append(aliasNodes, &kn, &vn)
	}
	aliases := yaml.Node{Kind: yaml.MappingNode, Content: aliasNodes}
	aliasesTitle := yaml.Node{Kind: yaml.ScalarNode, Value: "aliases", HeadComment: comment3}

	ancYaml := yaml.Node{Kind: yaml.MappingNode, Content: []*yaml.Node{&prefixesTitle, &prefixes, &prefixHSMSubrolesTitle, &prefixHSMSubroles, &aliasesTitle, &aliases}}

	ancFile, err := os.Create(application_node_config)

	if err != nil {
		log.Fatalln(err)
	}
	defer ancFile.Close()
	_, err = ancFile.WriteString("---\n")
	e := yaml.NewEncoder(ancFile)
	defer e.Close()
	e.SetIndent(2)
	err = e.Encode(ancYaml)
	log.Printf("Created %v from SHCD data\n", application_node_config)
	return err
}

// ValidateSchema compares a JSON file to the defined schema file
func ValidateSchema(f string, s string) (bool, error) {
	// First validate the file passed in conforms to the schema
	schema := "file://" + s
	schemaLoader := gojsonschema.NewReferenceLoader(schema)
	jsonFile := "file://" + f
	documentLoader := gojsonschema.NewReferenceLoader(jsonFile)

	result, err := gojsonschema.Validate(schemaLoader, documentLoader)

	if err != nil {
		return false, fmt.Errorf("%s", err)
	}

	// If the json passed in does not meet the schema requirements, error
	if !result.Valid() {

		for _, desc := range result.Errors() {
			return false, fmt.Errorf("SHCD schema error: %s", desc)
		}

	}

	return true, nil
}

// ParseSHCD accepts a machine-readable SHCD and produces an Shcd object, which can be used throughout csi
// It is the golang and csi equivalent of the shcd.json file generated by canu
func ParseSHCD(f []byte) (Shcd, error) {
	var shcd Shcd

	// unmarshall it
	err := json.Unmarshal(f, &shcd)

	if err != nil {
		fmt.Println("error:", err)
		return shcd, err
	}

	return shcd, nil
}
