name: Continuous Integration

on:
  push:
    branches:
      - '*'
    tags:
      # semver tags:
      - 'v[12].[0-9]+.[0-9]+'
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Lint and Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Lint
      run: |
        make tools
        make lint

    - name: Test
      run: make test
