name: GitHub Pages

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: "1.19"

      - name: makedocs
        run: go run main.go makedocs ./hugo/content/commands

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: |
          pushd hugo
          hugo --enableGitInfo --themesDir themes/ --minify
          popd

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          destination_dir: ./docs
