name: Test

on:
  push:
    branches:
      - '*'
    tags:
      # semver tags:
      - 'v?[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main
      - 'release/**'

jobs:

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24

    - name: Test
      run: |
        make tools
        make test
